backend:
  name: github
  repo: abdullah-lajam/my-digital-blog # Updated with user's repo
  branch: master
  client_id: Ov23linH8mC7YEVdCfJz # Updated with user's Client ID
  # site_domain: 4000-i7zp1rxhhngb1inorip5m-f7f16f53.manusvm.computer # Temporary domain for local testing with OAuth

media_folder: "assets/uploads" # Folder where user uploaded files should go
publish_mode: editorial_workflow # Enable editorial workflow

collections:
  - name: "ai"
    label: "الذكاء الاصطناعي"
    folder: "_ai"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "الصورة البارزة", name: "image", widget: "image", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown"}
      - {label: "التصنيفات", name: "tags", widget: "list", required: false}

  - name: "elearning"
    label: "التعليم الإلكتروني"
    folder: "_elearning"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "الصورة البارزة", name: "image", widget: "image", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown"}
      - {label: "التصنيفات", name: "tags", widget: "list", required: false}

  - name: "business"
    label: "إدارة الأعمال"
    folder: "_business"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "الصورة البارزة", name: "image", widget: "image", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown"}
      - {label: "التصنيفات", name: "tags", widget: "list", required: false}

  - name: "humanities"
    label: "إنسانيات"
    folder: "_humanities"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "الصورة البارزة", name: "image", widget: "image", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown"}
      - {label: "التصنيفات", name: "tags", widget: "list", required: false}

  - name: "misc"
    label: "تدوينات متفرقة"
    folder: "_misc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "الصورة البارزة", name: "image", widget: "image", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown"}
      - {label: "التصنيفات", name: "tags", widget: "list", required: false}

  - name: "pages"
    label: "الصفحات"
    files:
      - file: "aboutme.md"
        label: "عني"
        name: "about"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "العنوان", name: "title", widget: "string"}
          - {label: "الرابط الدائم", name: "permalink", widget: "string"}
          - {label: "المحتوى", name: "body", widget: "markdown"}

